name: Bedtime Reminder

on:
  schedule:
    - cron: '30 9 * * *'    # 09:30 UTC = 4:30 AM Central
  workflow_dispatch:      # lets you run it manually

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send bedtime ping
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_BEDTIME }}
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content":"🛌 It'\''s 4:30 AM—time to go to bed!"}' \
               $WEBHOOK
